drop table if exists tjsmx;
create table tjsmx
(
  scdm varchar2(2) default ' ',
  jllx varchar2(3) default ' ',
  jyfs varchar2(3) default ' ',
  jsfs varchar2(3) default ' ',
  ywlx varchar2(3) default ' ',
  qsbz varchar2(3) default ' ',
  ghlx varchar2(3) default ' ',
  jsbh varchar2(16) default ' ',
  cjbh varchar2(32) default ' ',
  sqbh varchar2(32) default ' ',
  wtbh varchar2(16) default ' ',
  jyrq int default 0 not null,
  qsrq int default 0 not null,
  jsrq int default 0 not null,
  qtrq int default 0 not null,
  wtsj varchar2(6) default ' ',
  cjsj varchar2(10) default ' ',
  xwh1 varchar2(6) default ' ',
  xwh2 varchar2(6) default ' ',
  xwhy varchar2(8) default ' ',
  jshy varchar2(8) default ' ',
  tghy varchar2(8) default ' ',
  zqzh varchar2(32) default ' ',
  zqdm1 varchar2(8) default ' ',
  zqdm2 varchar2(8) default ' ',
  zqlb varchar2(2) default ' ',
  ltlx varchar2(2) default ' ',
  qylb varchar2(2) default ' ',
  gpnf varchar2(4) default ' ',
  mmbz varchar2(2) default ' ',
  sl decimal default 0 not null,
  cjsl decimal default 0 not null,
  zjzh varchar2(32) default ' ',
  bz varchar2(3) default ' ',
  jg1 decimal default 0 not null,
  jg2 decimal default 0 not null,
  qsje decimal default 0 not null,
  yhs decimal default 0 not null,
  jsf decimal default 0 not null,
  ghf decimal default 0 not null,
  zgf decimal default 0 not null,
  sxf decimal default 0 not null,
  qtje1 decimal default 0 not null,
  qtje2 decimal default 0 not null,
  qtje3 decimal default 0 not null,
  sjsf decimal default 0 not null,
  jgdm varchar2(4) default ' ',
  fjsm varchar2(128) default ' ',
  record_id int default 0 not null,
  constraint tjsmx_0 primary key (record_id)
);

create index if not exists tjsmx_1 on tjsmx(zqzh);